title: "Next Job"
author: "Gean Ramos"
email: "nextjob@geanramos.com.br"
description: "Next Job – Porque procurar emprego não precisa ser complicado!"
permalink: '/:title.html'
image: "https://picsum.photos/600/363"
avatar: "https://geanramos.com.br/img/avatar.png"
baseurl: "/dev"
url: "https://dev.geanramos.com.br"
theme: minima
markdown: kramdown
paginate: 10
plugins:
  - jekyll-feed
  - jekyll-seo-tag
collections:
  tags:
    output: true
