name: Atualizar versão do blog

on:
  push:
    branches:
      - main  # Altere para a branch correta do seu projeto

jobs:
  update-json:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Extrair versão do log
        run: |
          VERSION=$(grep -oP 'ghcr.io/actions/jekyll-build-pages:v\K[0-9]+\.[0-9]+\.[0-9]+' .github/workflows/update-version.yml)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Atualizar arquivo JSON
        run: |
          jq '.version = env.VERSION' version.json > temp.json && mv temp.json version.json

      - name: Commit e push das alterações
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Atualizando versão do blog para ${{ env.VERSION }}"
